CREATE TABLE [dbo].[DoseRule](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DoseFrom] [int] NOT NULL,
	[DoseTo] [int] NOT NULL,
	[VaccineID] [int] NOT NULL,
	[Days] [int] NOT NULL,
 CONSTRAINT [PK_DoseRule] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DoseRule]  WITH CHECK ADD  CONSTRAINT [FK_DoseRule_Dose] FOREIGN KEY([DoseTo])
REFERENCES [dbo].[Dose] ([ID])
GO

ALTER TABLE [dbo].[DoseRule] CHECK CONSTRAINT [FK_DoseRule_Dose]
GO
ALTER TABLE [dbo].[DoseRule]  WITH CHECK ADD  CONSTRAINT [FK_DoseRule_Vaccine] FOREIGN KEY([VaccineID])
REFERENCES [dbo].[Vaccine] ([ID])
GO

ALTER TABLE [dbo].[DoseRule] CHECK CONSTRAINT [FK_DoseRule_Vaccine]