//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VaccineDose
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clinic
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string OffDays { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public Nullable<double> Lat { get; set; }
        public Nullable<double> Long { get; set; }
        public int DoctorID { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<bool> IsOnline { get; set; }
    
        public virtual Doctor Doctor { get; set; }
    }
}
