
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace VaccineDose
{

using System;
    using System.Collections.Generic;
    
public partial class Doctor
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Doctor()
    {

        this.Clinics = new HashSet<Clinic>();

        this.DoctorSchedules = new HashSet<DoctorSchedule>();

    }


    public int ID { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Email { get; set; }

    public string MobileNo { get; set; }

    public string Password { get; set; }

    public string PMDC { get; set; }

    public bool IsApproved { get; set; }

    public bool ShowPhone { get; set; }

    public bool ShowMobile { get; set; }

    public string PhoneNo { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Clinic> Clinics { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DoctorSchedule> DoctorSchedules { get; set; }

}

}
