//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VaccineDose
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoseRule
    {
        public int ID { get; set; }
        public int DoseFrom { get; set; }
        public int DoseTo { get; set; }
        public int VaccineID { get; set; }
        public int Days { get; set; }
    
        public virtual Vaccine Vaccine { get; set; }
    }
}
