//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VaccineDose
{
    using System;
    using System.Collections.Generic;
    
    public partial class FollowUp
    {
        public int ID { get; set; }
        public string Disease { get; set; }
        public Nullable<System.DateTime> NextVisitDate { get; set; }
        public Nullable<System.DateTime> CurrentVisitDate { get; set; }
        public int ChildID { get; set; }
        public int DoctorID { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<double> Height { get; set; }
        public Nullable<double> OFC { get; set; }
        public Nullable<double> BloodPressure { get; set; }
        public Nullable<double> BloodSugar { get; set; }
    
        public virtual Child Child { get; set; }
        public virtual Doctor Doctor { get; set; }
    }
}
