
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace VaccineDose
{

using System;
    using System.Collections.Generic;
    
public partial class Vaccine
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Vaccine()
    {

        this.Doses = new HashSet<Dose>();

    }


    public int ID { get; set; }

    public string Name { get; set; }

    public int MinAge { get; set; }

    public Nullable<int> MaxAge { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Dose> Doses { get; set; }

}

}
